/* generated by tools/gen-arch-headers.sh — do not edit */
#ifndef AGENTCELL_ARCH_AARCH64_H
#define AGENTCELL_ARCH_AARCH64_H

#define AC_AUDIT_ARCH AUDIT_ARCH_AARCH64

#define AC_SYS_execve 221
#define AC_SYS_openat 56
#define AC_SYS_connect 203
#define AC_SYS_clone 220
#define AC_SYS_clone3 435
#define AC_SYS_mount 40
#define AC_SYS_umount2 39
#define AC_SYS_pivot_root 41
#define AC_SYS_unshare 97
#define AC_SYS_setns 268
#define AC_SYS_bpf 280
#define AC_SYS_perf_event_open 241
#define AC_SYS_ptrace 117
#define AC_SYS_keyctl 219
#define AC_SYS_init_module 105
#define AC_SYS_finit_module 273
#define AC_SYS_delete_module 106
#define AC_SYS_kexec_load 104
#define AC_SYS_kexec_file_load 294
#define AC_SYS_reboot 142
#define AC_SYS_swapon 224
#define AC_SYS_swapoff 225
#define AC_SYS_acpi -1
#define AC_SYS_process_vm_readv 270
#define AC_SYS_process_vm_writev 271
#define AC_SYS_kcmp 272
#define AC_SYS_pidfd_getfd 438
#define AC_SYS_process_madvise 440
#define AC_SYS_process_mrelease 448
#define AC_SYS_open_by_handle_at 265
#define AC_SYS_name_to_handle_at 264
#define AC_SYS_fsopen 430
#define AC_SYS_fsconfig 431
#define AC_SYS_fsmount 432
#define AC_SYS_fspick 433
#define AC_SYS_move_mount 429
#define AC_SYS_open_tree 428
#define AC_SYS_mount_setattr 442
#define AC_SYS_add_key 217
#define AC_SYS_request_key 218
#define AC_SYS_fanotify_init 262
#define AC_SYS_clock_settime 112
#define AC_SYS_clock_settime64 404
#define AC_SYS_settimeofday 170
#define AC_SYS_adjtimex 171
#define AC_SYS_vhangup 58
#define AC_SYS_syslog 116
#define AC_SYS_quotactl 60
#define AC_SYS_quotactl_fd 443
#define AC_SYS_userfaultfd 282
#define AC_SYS_uselib -1
#define AC_SYS_lookup_dcookie 18
#define AC_SYS_io_uring_setup 425
#define AC_SYS_io_uring_enter 426
#define AC_SYS_io_uring_register 427
#define AC_SYS_vm86 -1
#define AC_SYS_vm86old -1
#define AC_SYS_ioperm -1
#define AC_SYS_iopl -1

#define AC_TRIP_X X(mount) X(umount2) X(pivot_root) X(unshare) X(setns) X(clone3) X(bpf) X(perf_event_open) X(ptrace) X(keyctl) X(init_module) X(delete_module) X(userfaultfd) X(io_uring_setup) X(fsopen) X(fsconfig) X(fsmount) X(fspick) X(move_mount) X(open_tree) X(mount_setattr)

#define AC_TP_mount mount
#define AC_TP_umount2 umount
#define AC_TP_pivot_root pivot_root
#define AC_TP_unshare unshare
#define AC_TP_setns setns
#define AC_TP_clone3 clone3
#define AC_TP_bpf bpf
#define AC_TP_perf_event_open perf_event_open
#define AC_TP_ptrace ptrace
#define AC_TP_keyctl keyctl
#define AC_TP_init_module init_module
#define AC_TP_delete_module delete_module
#define AC_TP_userfaultfd userfaultfd
#define AC_TP_io_uring_setup io_uring_setup
#define AC_TP_fsopen fsopen
#define AC_TP_fsconfig fsconfig
#define AC_TP_fsmount fsmount
#define AC_TP_fspick fspick
#define AC_TP_move_mount move_mount
#define AC_TP_open_tree open_tree
#define AC_TP_mount_setattr mount_setattr
#define AC_TP_ioperm ioperm
#define AC_TP_iopl iopl

/* {nr, name} pairs — absent syscalls are simply left out */
struct ac_sys { int nr; const char *name; };
#define AC_SYSCALL_TAB \
  { 40, "mount" }, \
  { 39, "umount2" }, \
  { 41, "pivot_root" }, \
  { 97, "unshare" }, \
  { 268, "setns" }, \
  { 280, "bpf" }, \
  { 241, "perf_event_open" }, \
  { 117, "ptrace" }, \
  { 219, "keyctl" }, \
  { 105, "init_module" }, \
  { 273, "finit_module" }, \
  { 106, "delete_module" }, \
  { 104, "kexec_load" }, \
  { 294, "kexec_file_load" }, \
  { 142, "reboot" }, \
  { 224, "swapon" }, \
  { 225, "swapoff" }, \
  { 270, "process_vm_readv" }, \
  { 271, "process_vm_writev" }, \
  { 272, "kcmp" }, \
  { 438, "pidfd_getfd" }, \
  { 440, "process_madvise" }, \
  { 448, "process_mrelease" }, \
  { 265, "open_by_handle_at" }, \
  { 264, "name_to_handle_at" }, \
  { 430, "fsopen" }, \
  { 431, "fsconfig" }, \
  { 432, "fsmount" }, \
  { 433, "fspick" }, \
  { 429, "move_mount" }, \
  { 428, "open_tree" }, \
  { 442, "mount_setattr" }, \
  { 217, "add_key" }, \
  { 218, "request_key" }, \
  { 262, "fanotify_init" }, \
  { 112, "clock_settime" }, \
  { 404, "clock_settime64" }, \
  { 170, "settimeofday" }, \
  { 171, "adjtimex" }, \
  { 58, "vhangup" }, \
  { 116, "syslog" }, \
  { 60, "quotactl" }, \
  { 443, "quotactl_fd" }, \
  { 282, "userfaultfd" }, \
  { 18, "lookup_dcookie" }, \
  { 425, "io_uring_setup" }, \
  { 426, "io_uring_enter" }, \
  { 427, "io_uring_register" },

#endif /* AGENTCELL_ARCH_AARCH64_H */
