/* generated by tools/gen-arch-headers.sh — do not edit */
#ifndef AGENTCELL_ARCH_X86_64_H
#define AGENTCELL_ARCH_X86_64_H

#define AC_AUDIT_ARCH AUDIT_ARCH_X86_64

#define AC_SYS_execve 59
#define AC_SYS_openat 257
#define AC_SYS_connect 42
#define AC_SYS_clone 56
#define AC_SYS_clone3 435
#define AC_SYS_mount 165
#define AC_SYS_umount2 166
#define AC_SYS_pivot_root 155
#define AC_SYS_unshare 272
#define AC_SYS_setns 308
#define AC_SYS_bpf 321
#define AC_SYS_perf_event_open 298
#define AC_SYS_ptrace 101
#define AC_SYS_keyctl 250
#define AC_SYS_init_module 175
#define AC_SYS_finit_module 313
#define AC_SYS_delete_module 176
#define AC_SYS_kexec_load 246
#define AC_SYS_kexec_file_load 320
#define AC_SYS_reboot 169
#define AC_SYS_swapon 167
#define AC_SYS_swapoff 168
#define AC_SYS_acpi -1
#define AC_SYS_process_vm_readv 310
#define AC_SYS_process_vm_writev 311
#define AC_SYS_kcmp 312
#define AC_SYS_pidfd_getfd 438
#define AC_SYS_process_madvise 440
#define AC_SYS_process_mrelease 448
#define AC_SYS_open_by_handle_at 304
#define AC_SYS_name_to_handle_at 303
#define AC_SYS_fsopen 430
#define AC_SYS_fsconfig 431
#define AC_SYS_fsmount 432
#define AC_SYS_fspick 433
#define AC_SYS_move_mount 429
#define AC_SYS_open_tree 428
#define AC_SYS_mount_setattr 442
#define AC_SYS_add_key 248
#define AC_SYS_request_key 249
#define AC_SYS_fanotify_init 300
#define AC_SYS_clock_settime 227
#define AC_SYS_clock_settime64 -1
#define AC_SYS_settimeofday 164
#define AC_SYS_adjtimex 159
#define AC_SYS_vhangup 153
#define AC_SYS_syslog 103
#define AC_SYS_quotactl 179
#define AC_SYS_quotactl_fd 443
#define AC_SYS_userfaultfd 323
#define AC_SYS_uselib 134
#define AC_SYS_lookup_dcookie 212
#define AC_SYS_io_uring_setup 425
#define AC_SYS_io_uring_enter 426
#define AC_SYS_io_uring_register 427
#define AC_SYS_vm86 -1
#define AC_SYS_vm86old -1
#define AC_SYS_ioperm 173
#define AC_SYS_iopl 172

#define AC_TRIP_X X(mount) X(umount2) X(pivot_root) X(unshare) X(setns) X(clone3) X(bpf) X(perf_event_open) X(ptrace) X(keyctl) X(init_module) X(delete_module) X(userfaultfd) X(io_uring_setup) X(fsopen) X(fsconfig) X(fsmount) X(fspick) X(move_mount) X(open_tree) X(mount_setattr) X(ioperm) X(iopl)

#define AC_TP_mount mount
#define AC_TP_umount2 umount
#define AC_TP_pivot_root pivot_root
#define AC_TP_unshare unshare
#define AC_TP_setns setns
#define AC_TP_clone3 clone3
#define AC_TP_bpf bpf
#define AC_TP_perf_event_open perf_event_open
#define AC_TP_ptrace ptrace
#define AC_TP_keyctl keyctl
#define AC_TP_init_module init_module
#define AC_TP_delete_module delete_module
#define AC_TP_userfaultfd userfaultfd
#define AC_TP_io_uring_setup io_uring_setup
#define AC_TP_fsopen fsopen
#define AC_TP_fsconfig fsconfig
#define AC_TP_fsmount fsmount
#define AC_TP_fspick fspick
#define AC_TP_move_mount move_mount
#define AC_TP_open_tree open_tree
#define AC_TP_mount_setattr mount_setattr
#define AC_TP_ioperm ioperm
#define AC_TP_iopl iopl

/* {nr, name} pairs — absent syscalls are simply left out */
struct ac_sys { int nr; const char *name; };
#define AC_SYSCALL_TAB \
  { 165, "mount" }, \
  { 166, "umount2" }, \
  { 155, "pivot_root" }, \
  { 272, "unshare" }, \
  { 308, "setns" }, \
  { 321, "bpf" }, \
  { 298, "perf_event_open" }, \
  { 101, "ptrace" }, \
  { 250, "keyctl" }, \
  { 175, "init_module" }, \
  { 313, "finit_module" }, \
  { 176, "delete_module" }, \
  { 246, "kexec_load" }, \
  { 320, "kexec_file_load" }, \
  { 169, "reboot" }, \
  { 167, "swapon" }, \
  { 168, "swapoff" }, \
  { 310, "process_vm_readv" }, \
  { 311, "process_vm_writev" }, \
  { 312, "kcmp" }, \
  { 438, "pidfd_getfd" }, \
  { 440, "process_madvise" }, \
  { 448, "process_mrelease" }, \
  { 304, "open_by_handle_at" }, \
  { 303, "name_to_handle_at" }, \
  { 430, "fsopen" }, \
  { 431, "fsconfig" }, \
  { 432, "fsmount" }, \
  { 433, "fspick" }, \
  { 429, "move_mount" }, \
  { 428, "open_tree" }, \
  { 442, "mount_setattr" }, \
  { 248, "add_key" }, \
  { 249, "request_key" }, \
  { 300, "fanotify_init" }, \
  { 227, "clock_settime" }, \
  { 164, "settimeofday" }, \
  { 159, "adjtimex" }, \
  { 153, "vhangup" }, \
  { 103, "syslog" }, \
  { 179, "quotactl" }, \
  { 443, "quotactl_fd" }, \
  { 323, "userfaultfd" }, \
  { 134, "uselib" }, \
  { 212, "lookup_dcookie" }, \
  { 425, "io_uring_setup" }, \
  { 426, "io_uring_enter" }, \
  { 427, "io_uring_register" }, \
  { 173, "ioperm" }, \
  { 172, "iopl" },

#endif /* AGENTCELL_ARCH_X86_64_H */
