#!/usr/bin/env bash
# Regenerate src/arch/*.h from kernel uapi headers (RFC 0001, Gap 1).
#
# Syscall numbers are generated, never typed by hand: a wrong number in
# a seccomp deny list is a security hole.  Sources:
#   x86_64  : /usr/include/asm/unistd_64.h
#   aarch64 : /usr/include/asm-generic/unistd.h   (the arm64 table)
#
# Rerun after kernel header updates.  Committed output, so plain builds
# never need this script.
set -eu
OUT=$(cd "$(dirname "$0")/.." && pwd)/src/arch
mkdir -p "$OUT"

# names the BPF probes need individually
PROBES="execve openat connect clone clone3"
# the seccomp deny list == the TRIP (escape-attempt) naming table
DENY="mount umount2 pivot_root unshare setns bpf perf_event_open ptrace \
keyctl init_module finit_module delete_module kexec_load kexec_file_load \
reboot swapon swapoff acpi process_vm_readv process_vm_writev kcmp \
pidfd_getfd process_madvise process_mrelease open_by_handle_at \
name_to_handle_at fsopen fsconfig fsmount fspick move_mount open_tree \
mount_setattr add_key request_key fanotify_init clock_settime \
clock_settime64 settimeofday adjtimex vhangup syslog quotactl quotactl_fd \
userfaultfd uselib lookup_dcookie io_uring_setup io_uring_enter \
io_uring_register vm86 vm86old ioperm iopl"
# subset surfaced as TRIP events
TRIP="mount umount2 pivot_root unshare setns clone3 bpf perf_event_open \
ptrace keyctl init_module delete_module userfaultfd io_uring_setup \
fsopen fsconfig fsmount fspick move_mount open_tree mount_setattr ioperm iopl"

emit() {   # emit <archname> <AUDIT_ARCH> <header path>
    local arch=$1 audit=$2 hdr=$3
    local guard=AGENTCELL_ARCH_$(echo "$arch" | tr 'a-z' 'A-Z')_H
    {
        echo "/* generated by tools/gen-arch-headers.sh — do not edit */"
        echo "#ifndef $guard"
        echo "#define $guard"
        echo
        echo "#define AC_AUDIT_ARCH $audit"
        echo
        for s in $PROBES $DENY; do
            local nr=-1
            if [ -f "$hdr" ]; then
                local hit
                hit=$(grep -E "^#define __NR_${s}( |\$)" "$hdr" 2>/dev/null \
                      | awk '{print $3}' | head -1)
                if [ -n "$hit" ]; then nr=$hit; fi
            fi
            echo "#define AC_SYS_$s $nr"
        done
        echo
        # X-macro list of TRIP names present on this arch (nr >= 0)
        printf '#define AC_TRIP_X'
        for s in $TRIP; do
            local nr=-1
            if [ -f "$hdr" ]; then
                local hit
                hit=$(grep -E "^#define __NR_${s}( |\$)" "$hdr" 2>/dev/null \
                      | awk '{print $3}' | head -1)
                if [ -n "$hit" ]; then nr=$hit; fi
            fi
            if [ "$nr" -ge 0 ]; then printf ' X(%s)' "$s"; fi
        done
        echo
        echo
        # runtime table: deny list + attempt naming (absent syscalls skipped)
        echo "/* {nr, name} pairs — absent syscalls are simply left out */"
        echo "struct ac_sys { int nr; const char *name; };"
        echo "#define AC_SYSCALL_TAB \\"
        local first=1
        for s in $DENY; do
            local nr=-1
            if [ -f "$hdr" ]; then
                local hit
                hit=$(grep -E "^#define __NR_${s}( |\$)" "$hdr" 2>/dev/null \
                      | awk '{print $3}' | head -1)
                if [ -n "$hit" ]; then nr=$hit; fi
            fi
            if [ "$nr" -lt 0 ]; then continue; fi
            if [ $first = 1 ]; then first=0; else echo " \\"; fi
            printf '  { %s, "%s" },' "$nr" "$s"
        done
        echo
        echo
        echo "#endif /* $guard */"
    } > "$OUT/$arch.h"
    echo "wrote $OUT/$arch.h"
}

emit x86_64   AUDIT_ARCH_X86_64   /usr/include/asm/unistd_64.h
emit aarch64  AUDIT_ARCH_AARCH64  /usr/include/asm-generic/unistd.h

# selector header (hand-written, stable)
cat > "$OUT/syscalls.h" <<'EOF'
/* arch selector for AgentCell syscall abstraction (RFC 0001, Gap 1).
 * Works for native builds (__x86_64__/__aarch64__) AND clang BPF
 * builds (-D__TARGET_ARCH_x86 / -D__TARGET_ARCH_arm64). */
#ifndef AGENTCELL_SYSCALLS_H
#define AGENTCELL_SYSCALLS_H

#if defined(__x86_64__) || defined(__TARGET_ARCH_x86)
#include "x86_64.h"
#elif defined(__aarch64__) || defined(__TARGET_ARCH_arm64)
#include "aarch64.h"
#else
#error "AgentCell: unsupported architecture (x86_64 and aarch64 only)"
#endif

#endif
EOF
echo "wrote $OUT/syscalls.h"
